// @generated by protoc-gen-es v1.10.0
// @generated from file downward.proto (package echo_journey.downward, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum echo_journey.downward.DownwardMessageType
 */
export const DownwardMessageType = /*@__PURE__*/ proto3.makeEnum(
  "echo_journey.downward.DownwardMessageType",
  [
    {no: 0, name: "UNKNOWN"},
    {no: 1, name: "TUTOR_MESSAGE"},
    {no: 2, name: "WORD_CORRECT_MESSAGE"},
    {no: 3, name: "SENTENCE_CORRECT_MESSAGE"},
  ],
);

/**
 * @generated from message echo_journey.downward.DownwardMessage
 */
export const DownwardMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.downward.DownwardMessage",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(DownwardMessageType) },
    { no: 2, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message echo_journey.downward.TutorMessage
 */
export const TutorMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.downward.TutorMessage",
  () => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expected_messages", kind: "message", T: WordCorrectMessage, repeated: true },
  ],
);

/**
 * @generated from message echo_journey.downward.WordCorrectMessage
 */
export const WordCorrectMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.downward.WordCorrectMessage",
  () => [
    { no: 1, name: "word", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "initial_consonant", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "vowels", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tone", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message echo_journey.downward.SentenceCorrectMessage
 */
export const SentenceCorrectMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.downward.SentenceCorrectMessage",
  () => [
    { no: 1, name: "expected_messages", kind: "message", T: WordCorrectMessage, repeated: true },
    { no: 2, name: "messages", kind: "message", T: WordCorrectMessage, repeated: true },
    { no: 3, name: "suggestions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

