// @generated by protoc-gen-es v1.10.0
// @generated from file upward.proto (package echo_journey.upward, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum echo_journey.upward.UpwardMessageType
 */
export const UpwardMessageType = /*@__PURE__*/ proto3.makeEnum(
  "echo_journey.upward.UpwardMessageType",
  [
    {no: 0, name: "UNKNOWN"},
    {no: 1, name: "STUDENT_MESSAGE"},
    {no: 2, name: "AUDIO_MESSAGE"},
  ],
);

/**
 * @generated from message echo_journey.upward.UpwardMessage
 */
export const UpwardMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.upward.UpwardMessage",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(UpwardMessageType) },
    { no: 2, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message echo_journey.upward.StudentMessage
 */
export const StudentMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.upward.StudentMessage",
  () => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message echo_journey.upward.AudioMessage
 */
export const AudioMessage = /*@__PURE__*/ proto3.makeMessageType(
  "echo_journey.upward.AudioMessage",
  () => [
    { no: 1, name: "expected_sentence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "audio_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

